// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to PDFTextExtraction
class PDFTextExtractionBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PDFTextExtractionBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PDFTextExtractionBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Int8> extractText(
    ffi.Pointer<ffi.Int8> inFilePath,
    int startPage,
    int endPage,
    ffi.Pointer<ffi.NativeFunction<_typedefC_1>> callback,
  ) {
    return _extractText(
      inFilePath,
      startPage,
      endPage,
      callback,
    );
  }

  late final _extractText_ptr =
      _lookup<ffi.NativeFunction<_c_extractText>>('extractText');
  late final _dart_extractText _extractText =
      _extractText_ptr.asFunction<_dart_extractText>();
}

typedef _typedefC_1 = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8>,
);

typedef _c_extractText = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> inFilePath,
  ffi.Int32 startPage,
  ffi.Int32 endPage,
  ffi.Pointer<ffi.NativeFunction<_typedefC_1>> callback,
);

typedef _dart_extractText = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> inFilePath,
  int startPage,
  int endPage,
  ffi.Pointer<ffi.NativeFunction<_typedefC_1>> callback,
);
