// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to PDFTextExtraction
class PDFToTextBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PDFToTextBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PDFToTextBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int extractText(
    ffi.Pointer<ffi.Int8> fileName,
    int firstPage,
    int lastPage,
    ffi.Pointer<ffi.Int8> textOutEnc,
    ffi.Pointer<ffi.Int8> layout,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> textOutput,
    ffi.Pointer<ffi.NativeFunction<_typedefC_1>> logCallback,
    ffi.Pointer<ffi.Int8> ownerPassword,
    ffi.Pointer<ffi.Int8> userPassword,
  ) {
    return _extractText(
      fileName,
      firstPage,
      lastPage,
      textOutEnc,
      layout,
      textOutput,
      logCallback,
      ownerPassword,
      userPassword,
    );
  }

  late final _extractText_ptr =
      _lookup<ffi.NativeFunction<_c_extractText>>('extractText');
  late final _dart_extractText _extractText =
      _extractText_ptr.asFunction<_dart_extractText>();

  int getNumPages(
    ffi.Pointer<ffi.Int8> fileName,
    ffi.Pointer<ffi.NativeFunction<_typedefC_2>> logCallback,
    ffi.Pointer<ffi.Int8> ownerPassword,
    ffi.Pointer<ffi.Int8> userPassword,
  ) {
    return _getNumPages(
      fileName,
      logCallback,
      ownerPassword,
      userPassword,
    );
  }

  late final _getNumPages_ptr =
      _lookup<ffi.NativeFunction<_c_getNumPages>>('getNumPages');
  late final _dart_getNumPages _getNumPages =
      _getNumPages_ptr.asFunction<_dart_getNumPages>();
}

typedef _typedefC_1 = ffi.Void Function(
  ffi.Pointer<ffi.Int8>,
);

typedef _c_extractText = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> fileName,
  ffi.Int32 firstPage,
  ffi.Int32 lastPage,
  ffi.Pointer<ffi.Int8> textOutEnc,
  ffi.Pointer<ffi.Int8> layout,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> textOutput,
  ffi.Pointer<ffi.NativeFunction<_typedefC_1>> logCallback,
  ffi.Pointer<ffi.Int8> ownerPassword,
  ffi.Pointer<ffi.Int8> userPassword,
);

typedef _dart_extractText = int Function(
  ffi.Pointer<ffi.Int8> fileName,
  int firstPage,
  int lastPage,
  ffi.Pointer<ffi.Int8> textOutEnc,
  ffi.Pointer<ffi.Int8> layout,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> textOutput,
  ffi.Pointer<ffi.NativeFunction<_typedefC_1>> logCallback,
  ffi.Pointer<ffi.Int8> ownerPassword,
  ffi.Pointer<ffi.Int8> userPassword,
);

typedef _typedefC_2 = ffi.Void Function(
  ffi.Pointer<ffi.Int8>,
);

typedef _c_getNumPages = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> fileName,
  ffi.Pointer<ffi.NativeFunction<_typedefC_2>> logCallback,
  ffi.Pointer<ffi.Int8> ownerPassword,
  ffi.Pointer<ffi.Int8> userPassword,
);

typedef _dart_getNumPages = int Function(
  ffi.Pointer<ffi.Int8> fileName,
  ffi.Pointer<ffi.NativeFunction<_typedefC_2>> logCallback,
  ffi.Pointer<ffi.Int8> ownerPassword,
  ffi.Pointer<ffi.Int8> userPassword,
);
